/**
 * Builds design tokens (docs/07 §2, ADR-0005):
 *   build/tokens.css  → CSS custom properties, light on :root, dark under
 *                       prefers-color-scheme / [data-theme] (both directions)
 *   build/theme.js    → TypeScript theme object for Unistyles (mobile)
 * Deterministic output; committed so consumers need no build step.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { tokens } from '../src/tokens.js';

const out = resolve(import.meta.dirname, '..', 'build');
mkdirSync(out, { recursive: true });

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const colorVars = (theme: 'light' | 'dark') =>
  Object.entries(tokens.color[theme])
    .map(([k, v]) => `  --hg-${kebab(k)}: ${v};`)
    .join('\n');

const scalarVars = [
  ...Object.entries(tokens.space).map(([k, v]) => `  --hg-space-${k}: ${v};`),
  ...Object.entries(tokens.radius).map(([k, v]) => `  --hg-radius-${k}: ${v};`),
  ...Object.entries(tokens.font.size).map(([k, v]) => `  --hg-font-size-${k}: ${v};`),
  ...Object.entries(tokens.font.lineHeight).map(([k, v]) => `  --hg-line-height-${k}: ${v};`),
  ...Object.entries(tokens.font.family).map(
    ([k, v]) => `  --hg-font-${k}: ${v.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`,
  ),
  ...Object.entries(tokens.motion.duration).map(([k, v]) => `  --hg-duration-${k}: ${v};`),
  `  --hg-easing-standard: cubic-bezier(${tokens.motion.easing.standard.join(', ')});`,
  `  --hg-tracking-label: ${tokens.font.tracking.label};`,
  `  --hg-size-touch-target: ${tokens.size.touchTarget};`,
  `  --hg-size-focus-ring: ${tokens.size.focusRing};`,
].join('\n');

const css = `/* Generated by @heliograph/tokens — do not edit. Source: tokens/*.json */
:root {
  color-scheme: light dark;
${colorVars('light')}
${scalarVars}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars('dark')}
  }
}
:root[data-theme="dark"] {
${colorVars('dark')}
}
@media (prefers-reduced-motion: reduce) {
  :root {
    --hg-duration-state: 0ms;
    --hg-duration-panel: 0ms;
    --hg-duration-sheet: 0ms;
  }
}
`;
writeFileSync(resolve(out, 'tokens.css'), css);

const themeJs = `// Generated by @heliograph/tokens — do not edit.
export const tokens = ${JSON.stringify(tokens, null, 2)};
export const lightTheme = { colors: tokens.color.light, space: tokens.space, radius: tokens.radius, font: tokens.font, motion: tokens.motion, size: tokens.size };
export const darkTheme = { ...lightTheme, colors: tokens.color.dark };
`;
writeFileSync(resolve(out, 'theme.js'), themeJs);
writeFileSync(
  resolve(out, 'theme.d.ts'),
  `import type { Tokens } from '../dist/index.js';
export declare const tokens: Tokens;
export declare const lightTheme: { colors: Tokens['color']['light']; space: Tokens['space']; radius: Tokens['radius']; font: Tokens['font']; motion: Tokens['motion']; size: Tokens['size'] };
export declare const darkTheme: typeof lightTheme;
`,
);
process.stdout.write(`wrote ${out}/tokens.css, theme.js\n`);
