import type { PersonaDto } from '@heliograph/contracts';

export const personaFixture = (over: Partial<PersonaDto> = {}): PersonaDto => ({
  id: 'p1',
  workspaceId: 'ws',
  slug: 'deniz',
  name: 'Deniz Işık',
  niche: 'devops',
  language: 'tr',
  timezone: 'Europe/Istanbul',
  status: 'draft',
  warmupStartedAt: null,
  postingPolicy: {
    dailyPosts: { min: 3, max: 5 },
    dailyVideos: { min: 0, max: 2 },
    windows: [{ days: [1, 2, 3, 4, 5], from: '09:00', to: '12:00' }],
    jitterMinutes: 22,
    weekendFactor: 0.6,
  },
  voiceBible: {
    summary: '',
    audience: '',
    tone: [],
    register: 'plain',
    doList: [],
    dontList: [],
    preferredPhrases: [],
    bannedPhrases: [],
    experiencePool: [],
    samplePosts: [],
    emojiQuota: { min: 0, max: 2 },
    hashtagQuota: { min: 0, max: 4 },
    punctuation: { emDash: 'rare', exclamation: 'rare', lowercaseStarts: false },
  },
  visualKit: {
    palette: { primary: '#1F4E5A', accent: '#F2B705', ground: '#F4F5F1' },
    fontFamily: 'body',
    avatar: { kind: 'initials' },
    watermark: false,
  },
  topicProfile: { include: [], exclude: [], sourceWeights: {}, freshnessHours: 36 },
  engagementPolicy: {
    autoReply: false,
    replyRatio: 0.35,
    replyDelayMinutes: { min: 8, max: 180 },
    humanDraftPlatforms: ['x', 'tiktok'],
    quietHours: null,
  },
  qualityPolicy: { humanReview: 'always', minScore: 7, maxRegenerations: 2, aiDisclosure: 'auto' },
  missingForStart: ['voiceBible.summary', 'voiceBible.tone', 'topicProfile.include'],
  createdAt: '2026-09-04T12:00:00.000Z',
  updatedAt: '2026-09-04T12:00:00.000Z',
  ...over,
});
