/**
 * Seed for `policy_entries` (ADR-0011). Every value carries the source it was read from and a
 * max age; the staleness watcher will nag when a value is not re-verified in time.
 * Values verified on 2026-09-03 unless noted; ⚠ = third-party source only, re-verify first.
 */
export interface SeedPolicy {
  key: string;
  scope: 'global' | 'platform';
  scopeId: string | null;
  value: unknown;
  sourceUrl: string | null;
  maxAgeDays: number;
  notes?: string;
}

export const configSeed: SeedPolicy[] = [
  // Platform limits
  {
    key: 'platform.publish_limit_24h',
    scope: 'platform',
    scopeId: 'instagram',
    value: 100,
    sourceUrl: 'https://developers.facebook.com/docs/instagram-platform/content-publishing/',
    maxAgeDays: 30,
  },
  {
    key: 'platform.publish_limit_24h',
    scope: 'platform',
    scopeId: 'threads',
    value: 250,
    sourceUrl: 'https://developers.facebook.com/documentation/threads/overview',
    maxAgeDays: 30,
  },
  {
    key: 'platform.reply_limit_24h',
    scope: 'platform',
    scopeId: 'threads',
    value: 1000,
    sourceUrl: 'https://developers.facebook.com/documentation/threads/retrieve-and-manage-replies',
    maxAgeDays: 30,
  },
  {
    key: 'platform.upload_limit_24h',
    scope: 'platform',
    scopeId: 'youtube',
    value: 100,
    sourceUrl: 'https://developers.google.com/youtube/v3/determine_quota_cost',
    maxAgeDays: 30,
    notes: 'Separate videos.insert bucket; effective date reported by third parties as 2026-06 ⚠',
  },
  {
    key: 'platform.quota_units_per_day',
    scope: 'platform',
    scopeId: 'youtube',
    value: 10000,
    sourceUrl: 'https://developers.google.com/youtube/v3/getting-started',
    maxAgeDays: 30,
  },
  {
    key: 'platform.shorts_max_seconds',
    scope: 'platform',
    scopeId: 'youtube',
    value: 180,
    sourceUrl: 'https://support.google.com/youtube/answer/15424877',
    maxAgeDays: 90,
  },
  {
    key: 'platform.video_init_rate_per_min',
    scope: 'platform',
    scopeId: 'tiktok',
    value: 6,
    sourceUrl: 'https://developers.tiktok.com/doc/tiktok-api-v2-rate-limit',
    maxAgeDays: 30,
  },
  {
    key: 'platform.unaudited_max_users_24h',
    scope: 'platform',
    scopeId: 'tiktok',
    value: 5,
    sourceUrl: 'https://developers.tiktok.com/docs/en/content-sharing-guidelines',
    maxAgeDays: 30,
  },
  {
    key: 'platform.messages_per_second',
    scope: 'platform',
    scopeId: 'telegram',
    value: 30,
    sourceUrl: 'https://core.telegram.org/bots/faq',
    maxAgeDays: 90,
  },
  {
    key: 'platform.messages_per_minute_per_chat',
    scope: 'platform',
    scopeId: 'telegram',
    value: 20,
    sourceUrl: 'https://core.telegram.org/bots/faq',
    maxAgeDays: 90,
    notes: 'Stated by @BotSupport, not documented ⚠',
  },
  {
    key: 'platform.bot_upload_max_mb',
    scope: 'platform',
    scopeId: 'telegram',
    value: 50,
    sourceUrl: 'https://core.telegram.org/bots/api',
    maxAgeDays: 90,
  },
  // Platform prices
  {
    key: 'platform.price_per_post_usd',
    scope: 'platform',
    scopeId: 'x',
    value: 0.015,
    sourceUrl: 'https://docs.x.com/x-api/getting-started/pricing',
    maxAgeDays: 30,
    notes: 'Pay-per-use; per-call rate from third parties ⚠',
  },
  {
    key: 'platform.price_per_post_with_link_usd',
    scope: 'platform',
    scopeId: 'x',
    value: 0.2,
    sourceUrl: 'https://docs.x.com/x-api/getting-started/pricing',
    maxAgeDays: 30,
    notes: '⚠',
  },
  {
    key: 'platform.price_per_read_usd',
    scope: 'platform',
    scopeId: 'x',
    value: 0.005,
    sourceUrl: 'https://docs.x.com/x-api/getting-started/pricing',
    maxAgeDays: 30,
    notes: '⚠',
  },
  // Capabilities (what the official API allows for a third-party account)
  {
    key: 'platform.capabilities',
    scope: 'platform',
    scopeId: 'instagram',
    value: {
      publish: ['image', 'carousel', 'reel', 'story'],
      comments: 'full',
      dm: 'inbound_24h',
      insights: true,
      aiLabelField: null,
    },
    sourceUrl: 'https://developers.facebook.com/docs/instagram-platform/overview/',
    maxAgeDays: 60,
  },
  {
    key: 'platform.capabilities',
    scope: 'platform',
    scopeId: 'threads',
    value: {
      publish: ['text', 'image', 'video', 'carousel'],
      comments: 'full',
      dm: 'none',
      insights: true,
      aiLabelField: null,
    },
    sourceUrl: 'https://developers.facebook.com/documentation/threads/overview',
    maxAgeDays: 60,
  },
  {
    key: 'platform.capabilities',
    scope: 'platform',
    scopeId: 'tiktok',
    value: {
      publish: ['video', 'photo'],
      comments: 'business_api_only',
      dm: 'none',
      insights: 'own_videos',
      aiLabelField: null,
      auditRequired: true,
    },
    sourceUrl: 'https://developers.tiktok.com/doc/display-api-overview',
    maxAgeDays: 60,
  },
  {
    key: 'platform.capabilities',
    scope: 'platform',
    scopeId: 'youtube',
    value: {
      publish: ['video'],
      comments: 'full',
      dm: 'none',
      insights: true,
      aiLabelField: 'status.containsSyntheticMedia',
      auditRequired: true,
    },
    sourceUrl: 'https://developers.google.com/youtube/v3/docs/videos',
    maxAgeDays: 60,
  },
  {
    key: 'platform.capabilities',
    scope: 'platform',
    scopeId: 'x',
    value: {
      publish: ['text', 'image', 'video'],
      comments: 'reply_as_post',
      dm: 'limited',
      insights: 'paid_reads',
      automatedLabelRequired: true,
      aiReplyNeedsApproval: true,
    },
    sourceUrl: 'https://help.x.com/en/rules-and-policies/x-automation',
    maxAgeDays: 60,
  },
  {
    key: 'platform.capabilities',
    scope: 'platform',
    scopeId: 'telegram',
    value: {
      publish: ['text', 'image', 'video', 'media_group'],
      comments: 'discussion_group',
      dm: 'inbound_only',
      insights: 'views',
    },
    sourceUrl: 'https://core.telegram.org/bots/api',
    maxAgeDays: 90,
  },
  // Models and AI pricing
  {
    key: 'llm.writer.model',
    scope: 'global',
    scopeId: null,
    value: 'claude-opus-5',
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    maxAgeDays: 60,
  },
  {
    key: 'llm.classifier.model',
    scope: 'global',
    scopeId: null,
    value: 'claude-sonnet-5',
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    maxAgeDays: 60,
  },
  {
    key: 'llm.batch.model',
    scope: 'global',
    scopeId: null,
    value: 'claude-haiku-4-5',
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    maxAgeDays: 60,
  },
  {
    key: 'llm.price_per_mtok',
    scope: 'global',
    scopeId: null,
    value: {
      'claude-opus-5': { in: 5, out: 25, cacheRead: 0.5 },
      'claude-sonnet-5': { in: 2, out: 10, cacheRead: 0.2 },
      'claude-haiku-4-5': { in: 1, out: 5, cacheRead: 0.1 },
    },
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    maxAgeDays: 30,
  },
  {
    key: 'media.video.model',
    scope: 'global',
    scopeId: null,
    value: 'kling-3.0',
    sourceUrl: 'https://kling.ai/dev/pricing',
    maxAgeDays: 60,
    notes: 'Sora 2 API retired 2026-09-24; do not use',
  },
  {
    key: 'media.video.price_per_second_usd',
    scope: 'global',
    scopeId: null,
    value: 0.084,
    sourceUrl: 'https://kling.ai/dev/pricing',
    maxAgeDays: 30,
  },
  {
    key: 'media.tts.price_per_1k_chars_usd',
    scope: 'global',
    scopeId: null,
    value: 0.1,
    sourceUrl: 'https://elevenlabs.io/pricing/api',
    maxAgeDays: 30,
    notes: '⚠',
  },
  // Credits (docs/15 §3.2) — cost-derived, re-priced monthly
  {
    key: 'billing.credit_costs',
    scope: 'global',
    scopeId: null,
    value: {
      text_post: 2,
      carousel: 5,
      reply: 1,
      short_video_stock: 25,
      short_video_ai: 60,
      image: 3,
      voice_clone_training: 200,
    },
    sourceUrl: null,
    maxAgeDays: 30,
  },
  {
    key: 'billing.credit_warn_ratio',
    scope: 'global',
    scopeId: null,
    value: 0.8,
    sourceUrl: null,
    maxAgeDays: 180,
  },
  // Retention (docs/11 §14, docs/16)
  {
    key: 'retention.signals_days',
    scope: 'global',
    scopeId: null,
    value: 90,
    sourceUrl: null,
    maxAgeDays: 180,
  },
  {
    key: 'retention.interaction_text_days',
    scope: 'global',
    scopeId: null,
    value: 90,
    sourceUrl: null,
    maxAgeDays: 180,
  },
  {
    key: 'retention.account_deletion_grace_days',
    scope: 'global',
    scopeId: null,
    value: 30,
    sourceUrl: null,
    maxAgeDays: 180,
  },
  {
    key: 'retention.logs_days',
    scope: 'global',
    scopeId: null,
    value: 180,
    sourceUrl: null,
    maxAgeDays: 180,
  },
  // Legal document versions (legal/*)
  {
    key: 'legal.terms.version',
    scope: 'global',
    scopeId: null,
    value: '2026-09-03',
    sourceUrl: null,
    maxAgeDays: 180,
  },
  {
    key: 'legal.privacy.version',
    scope: 'global',
    scopeId: null,
    value: '2026-09-03',
    sourceUrl: null,
    maxAgeDays: 180,
  },
  {
    key: 'legal.kvkk_aydinlatma.version',
    scope: 'global',
    scopeId: null,
    value: '2026-09-03',
    sourceUrl: null,
    maxAgeDays: 180,
  },
  {
    key: 'legal.distance_sale.version',
    scope: 'global',
    scopeId: null,
    value: '2026-09-03',
    sourceUrl: null,
    maxAgeDays: 180,
  },
  {
    key: 'legal.eu_ai_act_art50_in_force',
    scope: 'global',
    scopeId: null,
    value: true,
    sourceUrl:
      'https://digital-strategy.ec.europa.eu/en/faqs/transparency-obligations-under-article-50-ai-act',
    maxAgeDays: 180,
  },
  // Warm-up and engagement defaults (persona policy defaults)
  {
    key: 'persona.warmup_days',
    scope: 'global',
    scopeId: null,
    value: 7,
    sourceUrl: null,
    maxAgeDays: 365,
  },
  {
    key: 'persona.reply_delay_minutes',
    scope: 'global',
    scopeId: null,
    value: { min: 4, max: 360 },
    sourceUrl: null,
    maxAgeDays: 365,
  },
  {
    key: 'persona.reply_ratio_default',
    scope: 'global',
    scopeId: null,
    value: 0.45,
    sourceUrl: null,
    maxAgeDays: 365,
  },
];
